{
  "path": "/documentation/callkit/cxerrorcodeincomingcallerror/code",
  "type": "Enumeration",
  "name": "CXErrorCodeIncomingCallError.Code",
  "desc": "Codes for errors that occur during incoming calls.",
  "items": [
    {
      "name": "case unknown",
      "desc": "An unknown error occurred."
    },
    {
      "name": "case unentitled",
      "desc": "The app isnâ€™t entitled to receive incoming calls."
    },
    {
      "name": "case callUUIDAlreadyExists",
      "desc": "The incoming call UUID already exists."
    },
    {
      "name": "case filteredByDoNotDisturb",
      "desc": "The incoming call is filtered because Do Not Disturb is active and the incoming caller is not a VIP."
    },
    {
      "name": "case filteredByBlockList",
      "desc": "The incoming call is filtered because the incoming caller has been blocked by the user."
    }
  ],
  "declaration": "enum CXErrorCodeIncomingCallError.Code : Int, _ErrorCodeProtocol, @unchecked Sendable",
  "conformsTo": [
    "Sendable"
  ]
}