{
  "path": "/documentation/cktooljs/cancellablepromise/3899342-catch",
  "type": "Instance Method",
  "name": "catch",
  "desc": "Tells CancellablePromise what callback to call on failure of the inner promise.",
  "items": [],
  "declaration": "CancellablePromise catch(\n    Function? onrejected\n);"
}