{
  "path": "/documentation/accelerate/vimage/error/internalerror",
  "type": "Enumeration Case",
  "name": "vImage.Error.internalError",
  "desc": "A serious error occurred inside vImage, which prevented vImage from continuing.",
  "items": [],
  "declaration": "case internalError"
}